AWSTemplateFormatVersion: 2010-09-09
Description: >-
    Infrastructure for StudySync
Parameters:
    ImageId:
        Description: 'AMI to use e.g.'
        Default: ami-0c02fb55956c7d316
        Type: String
    VpcId:
        Description: 'VPC used by the SG'
        Default: vpc-53ba612e
        Type: String
Resources:
    WebServer:
        Type: AWS::EC2::Instance
        Properties: 
            InstanceType: t2.micro
            ImageId: !Ref ImageId
            SecurityGroupIds:
                -   !GetAtt SecurityGroup.GroupId
            UserData:
                'Fn::Base64':
                    !Sub |
                        #!/usr/bin/env bash
                        sudo ec2-user
                        sudo yum install httpd -y
                        sudo service httpd start
                        sudo service httpd enable
    SecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId: !Ref VpcId
            GroupDescription: 'Open Port 80'
            SecurityGroupIngress:
                -   IpProtocol: tcp
                    FromPort: 80
                    ToPort: 80
                    CidrIp: "0.0.0.0/0"
                    
Outputs:
    PublicIp:
        Value: !GetAtt WebServer.PublicIp